### ISSUE TITLE
NTRs related to COVID-19/coronavirus diagnostics

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#158] opened 2020-03-25 23:57 UTC
Looking to add some new terms regarding coronavirus diagnostic screenings and evaluations:

From a general perspective we may benefit from a term such as,

**term: coronavinae infectious disease screening** ( refers to MONDO_0005719)
parent: disease screening
definition: Screening for virus diseases caused by the coronavirus genus. 

The following terms could be considered children of 'coronavinae infectious disease screening' or we may choose to put them under separate parents. I've suggested some options for both. Long and short, these are some pieces folks have been using for initial coronavirus diagnosis.

**term: screening for travel related infection** (open to other term name options here!)
parent: coronavinae infectious disease screening OR disease screening
definition: Evaluation of a patient's recent domestic or international travel history, often conducted alongside presentation of acute illness. 
Ref:https://www.doh.wa.gov/ForPublicHealthandHealthcareProviders/HealthcareProfessionsandFacilities/HealthcareAssociatedInfections/InfectionControlAssessmentandResponse/TravelrelatedInfectionScreening.  (still looking for publications to help define this term better, many relate to screening asymptomatic individuals in the airports following travel)

**term: radiography of the chest**
parent: 'therapeutic imaging procedure' (MAXO_0000005), but we likely need a broad radiography imaging procedure term there in general (see below)
definition: Radiographic imaging of the chest.
synonyms: chest x-ray, chest xray, chest radiography, chest radiograph
xref: NCIT:C38103
- note, this seems like something we should have, am I just missing it somewhere?

**term: radiography imaging procedure**
parent: therapeutic imaging procedure
definition: Conventional radiography produces a single image of an object by measuring the attenuation of an x-ray beam passing through it.
xref: NCIT:C38101
Ref: Wernick, M. N., Wirjadi, O., Chapman, D., Zhong, Z., Galatsanos, N. P., Yang, Y., ... & Muehleman, C. (2003). Multiple-image radiography. Physics in Medicine & Biology, 48(23), 3875.

For more of the diagnostic tools utilized for evaluating specimens:

**Term: Real-time PCR specimen test.** (not certain if 'test' is the most appropriate choice, what other options might we have?)
Parent: clinical laboratory procedure
Definition: A sensitive DNA analysis tool that can be used for genotyping, quantifying viral load, and gene copy number assays for specimens including whole blood, plasma, serum, and sputum. In RT-PCR, an RNA transcript is reverse transcribed into cDNA and amplified to qualitatively detect gene expression.
Synonyms: quantitative PCR, qPCR, RT-PCR, real-time polymerase chain reaction
xRefs: MMO:0000655, OBI_0000911
References: https://doi.org/10.1016/B978-0-12-405914-6.00003-2 , https://doi.org/10.1016/B978-0-12-802211-5.00009-6

I'll keep scoping around to see what other approaches folks are using.

**Comment by pnrobinson** [comment] 2020-03-26 00:03
+1 but Minor comment: radiography of the chest is not a 'therapeutic imaging procedure' 

 screening for travel related infection => This is probably a suboptimal term because it combines a procedure with a role/intention. 

coronavinae infectious disease screening => Perhaps simply "infectious disease screening" is sufficient. I am worried that we will wind up with one term for each microbe. Alternatively, consultation with infectious disease physician?

**Comment by LCCarmody** [comment] 2020-03-26 14:12
maybe the issue is the 'therapeutic imaging procedure' label?  Maybe we could make that more generic or call it 'therapeutic or diagnostic imaging procedure'?  The only reason I used the therapeutic in the label is to distinguish it from general microscopy that might not be specific for clinical use.

**Comment by LCCarmody** [comment] 2020-03-26 14:14
FTR, I am trying to compile some terms [here](https://docs.google.com/spreadsheets/d/143x6zaImPCKOe0a4ZrXFgOYqflVoxFN6YzDOLU0TZWk/edit?usp=sharing).   It is kind of sloppy right now, but feel free to add stuff.  It is just sort of a scratch sheet to figure out what types of terms we might need.

**Comment by pnrobinson** [comment] 2020-03-26 14:30
The items on the spreadsheet look all good to me. I would even add chloroquine even though it might not be as effective as some have claimed, because we might want to represent trials...

**Comment by LCCarmody** [comment] 2020-03-26 14:36
The only reason I said I wouldn't add is because I thought we were staying away from adding specific drugs.  Should we add it anyways?

**Comment by pnrobinson** [comment] 2020-03-26 14:38
I see, sorry, you were right! I wasn't thinking...

**Comment by laurenechan** [comment] 2020-03-26 15:36
@pnrobinson @LCCarmody 
Should I add 'infectious disease screening' , 'radiography imaging procedure', 'radiography of the chest', and 'Real-time PCR specimen test' to the spreadsheet and then start filling some of those spreadsheet terms in more? 
Also, are we interested in any term related to questionnaires about recent travel or is that best left out?

**Comment by LCCarmody** [comment] 2020-03-26 15:40
Sure, add them.  it may start to become more obvious how to extend the structure of MAXO to accommodate.  I think adding questionnaire's is fine, but I would like to stay away from what NCIt did where they added every question on questionnaires.  Maybe a general 'travel risk assessment questionaire' or something?

**Comment by LCCarmody** [comment] 2020-04-14 20:26
Most of these terms have been added in the new release (Yay!).  I will add the others to separate tickets and eventually close this ticket.  Feel free to add more to the google doc or individual tickets.  Just trying to contain this a bit.

**Comment by LCCarmody** [comment] 2020-04-28 14:09
Closing.  Nearly all terms have been added (thanks for the suggestions!). The remaining ones are in #168 #169 #166.

**Closed by LCCarmody** 2020-04-28 14:09 UTC
