### ISSUE TITLE
duplicate definitions

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/MAxO#218] opened 2021-02-17 16:43 UTC
Looks like nonsteroidal anti-inflammatory agent therapy has the same definition as anti-inflammatory agent therapy. It's causing some errors in ECTO.

**Comment by LCCarmody** [comment] 2021-02-17 20:14
Thanks. I will get to this soon.

**Comment by LCCarmody** [comment] 2021-02-22 17:54
Actually, I think the issue is that they had the same synonyms (and not the same definition).  This will be fixed in the next release.

**Closed** 2021-02-24 18:30 UTC
