### ISSUE TITLE
OAK cant handle maxo.json/owl/obo because of opaque error during parsing

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#362] opened 2022-12-05 00:22 UTC
Trying with maxo json/obo/owl throws various errors with the following code (and with phenol)
```
from oaklib.resource import OntologyResource
from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
oi = ProntoImplementation(OntologyResource(local=False, slug='maxo.json'))
oi = ProntoImplementation(resource)
```
e.g., 
```
ValueError: graphs[0].logicalDefinitionAxioms[0]: missing field `genusIds` at line 212757 column 9
```

**Comment by matentzn** [comment] 2023-01-24 11:14
@hrshdhgd can you look into this? I added it to your board with high priority.

**Comment by hrshdhgd** [comment] 2023-01-24 15:10
If you're not married to using `Pronto`, may I suggest using `SQLImplementation`? It is definitely faster than the former.

```
from oaklib.resource import OntologyResource
from oaklib.implementations.sqldb.sql_implementation import SqlImplementation

resource = OntologyResource(slug="obo:maxo")
oi = SqlImplementation(resource=resource)
```

**Comment by matentzn** [comment] 2023-01-24 17:03
@hrshdhgd I think it is a good workaround, but we really need to get obographs to be handled correctly in OAK - Peter may have a local version of maxo.json which he needs to query..

**Comment by pnrobinson** [comment] 2023-01-25 07:12
I think the problem is not in OAK, it is in obographs, and we cannot parse MAXO with phenol either.
In general, it is time for us to say goodbye to OBO, we need to stick to the one source of truth principle (sortof, because we have json and OWL for different downstream applications)

**Comment by matentzn** [comment] 2023-01-25 08:50
In this case, the problem is that the json parser which is provided by an external library is too strict. We investigated the format and it turned out to be fine;

The error with phenol, can you remind me where it is documented? Is there an issue?

**Comment by LCCarmody** [comment] 2024-07-25 18:12
Is this resolved?

**Comment by matentzn** [comment] 2024-07-25 18:15
Yes!

**Comment by LCCarmody** [comment] 2024-07-25 18:21
Thanks! closing.

**Closed by LCCarmody** 2024-07-25 18:21 UTC
Labels: bug
